name: Flutter Build APK

# هاد الكود بيشتغل أول ما تعمل Push أو Pull Request على فرع main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. سحب الكود من المستودع
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. تثبيت جافا (مهمة جداً للأندرويد)
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. تثبيت فلاتر
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # أو اتركها فاضية لجلب أحدث نسخة مستقرة
          channel: 'stable'

      # 4. قبول تراخيص أندرويد تلقائياً
      - name: Accept Android Licenses
        run: yes | flutter doctor --android-licenses

      # 5. تحميل المكتبات (http وغيرها)
      - name: Install dependencies
        run: flutter pub get

      # 6. بناء ملف الـ APK (نسخة Release)
      - name: Build APK
        run: flutter build apk --release

      # 7. رفع الملف الناتج عشان تقدر تحمله (استخدام v4 الأحدث)
      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-app-release
          path: build/app/outputs/flutter-apk/app-release.apk
